name: Tests
on: [ push ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', 3.11, 3.12]
        poetry-version: [ 1.8.3 ]
        django-version: [ 5.1.1 ]
        jwt-drf-version: [ 5.3.1 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install --only main,dev --all-extras
      - name: Upgrade django version
        run: |
          poetry run pip install "Django==${{ matrix.django-version }}"
      - name: Upgrade drf version
        run: |
          poetry run pip install "djangorestframework-simplejwt==${{ matrix.jwt-drf-version }}"
      - name: Echo env
        run: poetry run pip freeze | grep -E 'djangorestframework-simplejwt|Django'
      - name: Run tests
        run: poetry run py.test --capture=no #--cov-report term-missing --cov-report html --cov=jwt_drf_passwordless tests/
      # - name: Collect cov
      #   run: poetry run coverage xml
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     files: ./coverage.xml
      #     fail_ci_if_error: true
      #     verbose: true
